### ISSUE TITLE
Bazel `--incompatible_depset_union` breaks latex build 

### ISSUE THREAD

**Issue by qzmfranklin** [ProdriveTechnologies/bazel-latex#16]
[This line](https://github.com/ProdriveTechnologies/bazel-latex/blob/master/latex.bzl#L16) breaks the Bazel flag `--incompatible_depset_union` as of Bazel `0.26.0rc16`.

Error message was:
```text
ERROR: /home/zhongming/git/LogiOcean/examples/latex/BUILD:9:1: in _latex_pdf rule //examples/latex:helloworld:
Traceback (most recent call last):
        File "/home/zhongming/git/LogiOcean/examples/latex/BUILD", line 9
                _latex_pdf(name = 'helloworld')
        File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/external/bazel_latex/latex.bzl", line 3, in _latex_pdf_impl
                ctx.actions.run(mnemonic = "LuaLatex", executable ...", <4 more arguments>)
        File "/home/zhongming/.cache/bazel/_bazel_zhongming/2aea414f4d422ad78870bb37da8563ec/external/bazel_latex/latex.bzl", line 16, in ctx.actions.run
                toolchain.kpsewhich.files + toolchain.luatex.files
`+` operator on a depset is forbidden. See https://docs.bazel.build/versions/master/skylark/depsets.html for recommendations. Use --incompatible_depset_union=false to temporarily disable this check.
ERROR: Analysis of target '//examples/latex:helloworld' failed; build aborted: Analysis of target '//examples/latex:helloworld' failed; build aborted
```

**Comment by regisd** [comment]
Thanks for the super quick fix!
