### ISSUE TITLE
no such package '@bazel_latex_latexrun//' caused by patch: command not found

### ISSUE THREAD

**Issue by regisd** [ProdriveTechnologies/bazel-latex#5]
Thanks for wrapping everything in latexrun to improve error logging.

It works fine for me locally (bazel 0.18) but fails on Cirrus (bazel 0.16.1)

```
ERROR: /tmp/cirrus-ci-build/docs/BUILD:54:1: every rule of type _latex_pdf implicitly depends upon the target '@bazel_latex_latexrun//:latexrun', but this target could not be found because of: no such package '@bazel_latex_latexrun//': Traceback (most recent call last):
	File "/home/cirrus/.cache/bazel/_bazel_cirrus/b3ae12dd079012e10ed112b1996c540f/external/bazel_tools/tools/build_defs/repo/http.bzl", line 55
		patch(ctx)
	File "/home/cirrus/.cache/bazel/_bazel_cirrus/b3ae12dd079012e10ed112b1996c540f/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 79, in patch
		fail(("Error applying patch %s:\n%s%s...)))
Error applying patch @bazel_latex//:patches/latexrun-force-colors:
bash: patch: command not found
```

**Comment by regisd** [comment]
And that's probably a duplicate of https://github.com/bazelbuild/bazel/issues/5234
