### ISSUE TITLE
Switch CI to GitHub Actions

### ISSUE THREAD

**Issue by Kernald** [ProdriveTechnologies/bazel-latex#93]
- [x] Set up GitHub Actions (#91)
- [x] Either define a Windows toolchain or remove Windows from the matrix (#94, #95)
- [ ] Fix the cache directories - apparently the cache directories aren't created and GitHub Actions isn't saving anything
- [ ] Figure out why the example targets are building on macOS and locally but not on Ubuntu on CI
- [ ] Clean-up Cirrus

**Comment by Kernald** [comment]
Looking into the Ubuntu issue, building the same thing on an Ubuntu 20.04 VM (which seems to be what `ubuntu-latest` is at the moment on GitHub CI) works fine.

From https://github.com/ProdriveTechnologies/bazel-latex/actions/runs/3216875591/jobs/5259232208:
 - This isn't specific to Ubuntu 20.04 (same happens on 22.04)
 - It seems to be quite specific to biber, as the examples are failing but packages build fine. Output:
```
ERROR: /home/runner/work/bazel-latex/bazel-latex/example/BUILD.bazel:16:15: LuaLatex example/my_dvi_report.dvi failed: (Exit 1): tool_wrapper_py failed: error executing command bazel-out/host/bin/tool_wrapper_py '--dep-tool=external/texlive_bin__x86_64-linux/kpsewhich' '--dep-tool=external/texlive_bin__x86_64-linux/luatex' '--dep-tool=external/texlive_bin__x86_64-linux/bibtex' ... (remaining 11 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
external/bazel_latex_latexrun/latexrun exited (1) with:
error: Can't chmod() /tmp/par-72756e6e6572/cache-d31705f85102d579faeed3daf7f26b3d37aae75b/cc949ed7.so.27: No such file or directory 
 at /tmp/par-72756e6e6572/cache-d31705f85102d579faeed3daf7f26b3d37aae75b/inc/lib/IPC/Cmd.pm line 37.
Attempt to reload Time/HiRes.pm aborted.
Compilation failed in require at /tmp/par-72756e6e6572/cache-d31705f85102d579faeed3daf7f26b3d37aae75b/inc/lib/Data/Uniqid.pm line 27.
BEGIN failed--compilation aborted at /tmp/par-72756e6e6572/cache-d31705f85102d579faeed3daf7f26b3d37aae75b/inc/lib/Data/Uniqid.pm line 27.
Compilation failed in require at /tmp/par-72756e6e6572/cache-d31705f85102d579faeed3daf7f26b3d37aae75b/inc/lib/Biber/Entry/Name.pm line 14.
BEGIN failed--compilation aborted at /tmp/par-72756e6e6572/cache-d31705f85102d579faeed3daf7f26b3d37aae75b/inc/lib/Biber/Entry/Name.pm line 14.
Compilation failed in require at /tmp/par-72756e6e6572/cache-d31705f85102d579faeed3daf7f26b3d37aae75b/inc/lib/Biber/Utils.pm line 20.
BEGIN failed--compilation aborted at /tmp/par-72756e6e6572/cache-d31705f85102d579faeed3daf7f26b3d37aae75b/inc/lib/Biber/Utils.pm line 20.
Compilation failed in require at /tmp/par-72756e6e6572/cache-d31705f85102d579faeed3daf7f26b3d37aae75b/inc/lib/Biber/Internals.pm line 8.
BEGIN failed--compilation aborted at /tmp/par-72756e6e6572/cache-d31705f85102d579faeed3daf7f26b3d37aae75b/inc/lib/Biber/Internals.pm line 8.
Compilation failed in require at /loader/HASH(0x1b78540)/parent.pm line 16.
BEGIN failed--compilation aborted at /tmp/par-72756e6e6572/cache-d31705f85102d579faeed3daf7f26b3d37aae75b/inc/lib/Biber.pm line 5.
Compilation failed in require at script/biber line 17.
BEGIN failed--compilation aborted at script/biber line 17.
Traceback (most recent call last):
  File "/home/runner/.cache/bazel/_bazel_runner/035df82e99f563e965083a2d561c9b1c/sandbox/linux-sandbox/1/execroot/bazel_latex/bin/latexrun", line 1980, in <module>
    main()
  File "/home/runner/.cache/bazel/_bazel_runner/035df82e99f563e965083a2d561c9b1c/sandbox/linux-sandbox/1/execroot/bazel_latex/bin/latexrun", line 169, in main
    stable = run_tasks(tasks, args.max_iterations)
  File "/home/runner/.cache/bazel/_bazel_runner/035df82e99f563e965083a2d561c9b1c/sandbox/linux-sandbox/1/execroot/bazel_latex/bin/latexrun", line 558, in run_tasks
    task.run()
  File "/home/runner/.cache/bazel/_bazel_runner/035df82e99f563e965083a2d561c9b1c/sandbox/linux-sandbox/1/execroot/bazel_latex/bin/latexrun", line 655, in run
    result = self._execute()
  File "/home/runner/.cache/bazel/_bazel_runner/035df82e99f563e965083a2d561c9b1c/sandbox/linux-sandbox/1/execroot/bazel_latex/bin/latexrun", line 1657, in _execute
    inputs, auxnames, outbase = self.__parse_inputs(stdout, cwd, env)
  File "/home/runner/.cache/bazel/_bazel_runner/035df82e99f563e965083a2d561c9b1c/sandbox/linux-sandbox/1/execroot/bazel_latex/bin/latexrun", line 1749, in __parse_inputs
    outbase = auxnames[0][:-4]
IndexError: list index out of range
```

(The out of range is just luatex failing to parse the logs above and seems to just be a red herring.)

**Comment by Kernald** [comment]
I'll disable Ubuntu on GitHub Actions for now, as it's covered by Cirrus CI, to unblock other PRs.

**Comment by solsjo** [comment]
Ubuntu and Mac OS X now runs in the github actions CI, in [svg support](https://github.com/ProdriveTechnologies/bazel-latex/pull/87)
